
//get all the spots
GET http://localhost:3000/api/v1/stores


//add another spot 
POST http://localhost:3000/api/v1/stores 


//admin login 

POST http://localhost:3000/api/v1/admin


//post a new data 

POST http://localhost:3000/api/v1/data/

//get new data 

GET http://localhost:3000/api/v1/data/